### PR TITLE
Wording changes & signup form

### PR DESCRIPTION
**Pull request by briankung**

### CODE REVIEW

**Comment by briankung** [comment]
screen shot 2016-11-20 at 9 04 24 pm

**Comment by briankung** [comment]
Ignore the navbar, that's just an artifact from the screenshotting service I used.

shot-20161121-2837-18xv2qv

**Comment by wsf246** [comment]
Sweet, this is perfect.  We can either merge now or we can wait to create a tutorial page.  I'm considering using that tutorial js library you had shared with me.

**Comment by briankung** [comment]
We should probably just make a video. I'm going to merge to master

**Pull request merged**
