### PR TITLE
Prevents references from being added or destroyed if user cannot edit

### PR DESCRIPTION
**Pull request by briankung**
**Problem:** An unauthorized user could add and remove references to another user's list

**Solution:** Prevent unauthorized users from adding or removing references on another user's list

**Complications:** Not sure if I got all the cases

**Feature Changelog:**

- Prevent unauthorized users from adding or removing references on another user's list

### CODE REVIEW

**Comment by wsf246** [comment]
what do you think about removing the search bar and the 'add reference' forms if they are not contributors.  Or disabling them.

**Comment by briankung** [comment]
Probably a good idea

**Comment by wsf246** [comment]
If this is good, I'm gonna merge.  We can disable forms and the such on a separate PR.

**Comment by briankung** [comment]
Good for now. I left my laptop at home by accident and I'm out. Feel free
to pull and disable the forms yourself. Just push up to the PR branch

**Comment by briankung** [comment]
Or we could do it in a separate PR, up to you. I won't have my laptop for
another hour at least

**Comment by wsf246** [comment]
you do you man, I'll merge for now.

**Comment by briankung** [comment]
We also need to limit who can delete comments. Probably only a moderator?

**Comment by wsf246** [comment]
agreed

**Pull request merged**
