### PR TITLE
Fix reference sort

### PR DESCRIPTION
**Pull request by wsf246**
**Problem:** 
#123

**Solution:** 
Add sort back to Users/Lists#Show

### CODE REVIEW

**Comment by wsf246** [comment]
I was looking at the cached votes up.  I had an issue with one but I destroyed the paper and re-added it and it didn't have the same problem.  I'll keep playing with it to see if I can reproduce the cached votes up not updating, but I suspect it's just an issue with data that was created prior to the initial migration.  WIP

**Comment by briankung** [comment]
No worries, if you don't see it, just move on. I was just reminding you of
the possibility.

**Comment by briankung** [comment]
This PR looks good to merge to me

**Comment by wsf246** [comment]
yea, it was not updating for 1 but it wasn't happening for the others.  I'm gonna merge this.

**Comment by briankung** [comment]
Woot

**Pull request merged**
