### PR TITLE
Pubmed json

### PR DESCRIPTION
**Pull request by wsf246**

### CODE REVIEW

**Comment by wsf246** [comment]
This creates a module that lets you input search terms and get metadata for 20 papers

**Comment by wsf246** [comment]
there might be an error from nil results, let me check before you merge.

**Comment by wsf246** [comment]
looks like it will just return an empty hash, which is fine.  let me know if you have any questions.

**Comment by briankung** [comment]
Another file naming convention would be to name it `pubmed_search.rb`

**Comment by wsf246** [comment]
done, if it looks good, we can merge

**Comment by briankung** [comment]
Oh yeah, try not to merge your own stuff. I would have had some comments on
that.

**Comment by wsf246** [comment]
sorry, was trying to see if I could get the module to work with a view I'm
making but didn't want to not have all the changes we had just merged into
master.  I'll slow my roll.

**Pull request merged**
